/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/react-query"
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query"

import axios from "axios"
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios"

import type {
  DashboardGetParams,
  HTTPValidationError,
  ReproducibilityData,
  ReproducibleApiApiReproducibleGetParams,
  ReproducibleStatusReproducibleGetParams,
  StatusBannerApiApiStatusBannerGet200,
} from "../model"

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

/**
 * @summary Reproducible Api
 */
export const reproducibleApiApiReproducibleGet = (
  params?: ReproducibleApiApiReproducibleGetParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ReproducibilityData>> => {
  return axios.get(`https://builds.flathub.org/api/reproducible`, {
    ...options,
    params: { ...params, ...options?.params },
  })
}

export const getReproducibleApiApiReproducibleGetQueryKey = (
  params?: ReproducibleApiApiReproducibleGetParams,
) => {
  return [
    `https://builds.flathub.org/api/reproducible`,
    ...(params ? [params] : []),
  ] as const
}

export const getReproducibleApiApiReproducibleGetQueryOptions = <
  TData = Awaited<ReturnType<typeof reproducibleApiApiReproducibleGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params?: ReproducibleApiApiReproducibleGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof reproducibleApiApiReproducibleGet>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getReproducibleApiApiReproducibleGetQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof reproducibleApiApiReproducibleGet>>
  > = ({ signal }) =>
    reproducibleApiApiReproducibleGet(params, { signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof reproducibleApiApiReproducibleGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReproducibleApiApiReproducibleGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof reproducibleApiApiReproducibleGet>>
>
export type ReproducibleApiApiReproducibleGetQueryError =
  AxiosError<HTTPValidationError>

export function useReproducibleApiApiReproducibleGet<
  TData = Awaited<ReturnType<typeof reproducibleApiApiReproducibleGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params: undefined | ReproducibleApiApiReproducibleGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof reproducibleApiApiReproducibleGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reproducibleApiApiReproducibleGet>>,
          TError,
          Awaited<ReturnType<typeof reproducibleApiApiReproducibleGet>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useReproducibleApiApiReproducibleGet<
  TData = Awaited<ReturnType<typeof reproducibleApiApiReproducibleGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params?: ReproducibleApiApiReproducibleGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof reproducibleApiApiReproducibleGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reproducibleApiApiReproducibleGet>>,
          TError,
          Awaited<ReturnType<typeof reproducibleApiApiReproducibleGet>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useReproducibleApiApiReproducibleGet<
  TData = Awaited<ReturnType<typeof reproducibleApiApiReproducibleGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params?: ReproducibleApiApiReproducibleGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof reproducibleApiApiReproducibleGet>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Reproducible Api
 */

export function useReproducibleApiApiReproducibleGet<
  TData = Awaited<ReturnType<typeof reproducibleApiApiReproducibleGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params?: ReproducibleApiApiReproducibleGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof reproducibleApiApiReproducibleGet>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getReproducibleApiApiReproducibleGetQueryOptions(
    params,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Status Banner Api
 */
export const statusBannerApiApiStatusBannerGet = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<StatusBannerApiApiStatusBannerGet200>> => {
  return axios.get(`https://builds.flathub.org/api/status-banner`, options)
}

export const getStatusBannerApiApiStatusBannerGetQueryKey = () => {
  return [`https://builds.flathub.org/api/status-banner`] as const
}

export const getStatusBannerApiApiStatusBannerGetQueryOptions = <
  TData = Awaited<ReturnType<typeof statusBannerApiApiStatusBannerGet>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof statusBannerApiApiStatusBannerGet>>,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getStatusBannerApiApiStatusBannerGetQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof statusBannerApiApiStatusBannerGet>>
  > = ({ signal }) =>
    statusBannerApiApiStatusBannerGet({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof statusBannerApiApiStatusBannerGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StatusBannerApiApiStatusBannerGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof statusBannerApiApiStatusBannerGet>>
>
export type StatusBannerApiApiStatusBannerGetQueryError = AxiosError<unknown>

export function useStatusBannerApiApiStatusBannerGet<
  TData = Awaited<ReturnType<typeof statusBannerApiApiStatusBannerGet>>,
  TError = AxiosError<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof statusBannerApiApiStatusBannerGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof statusBannerApiApiStatusBannerGet>>,
          TError,
          Awaited<ReturnType<typeof statusBannerApiApiStatusBannerGet>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useStatusBannerApiApiStatusBannerGet<
  TData = Awaited<ReturnType<typeof statusBannerApiApiStatusBannerGet>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof statusBannerApiApiStatusBannerGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof statusBannerApiApiStatusBannerGet>>,
          TError,
          Awaited<ReturnType<typeof statusBannerApiApiStatusBannerGet>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useStatusBannerApiApiStatusBannerGet<
  TData = Awaited<ReturnType<typeof statusBannerApiApiStatusBannerGet>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof statusBannerApiApiStatusBannerGet>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Status Banner Api
 */

export function useStatusBannerApiApiStatusBannerGet<
  TData = Awaited<ReturnType<typeof statusBannerApiApiStatusBannerGet>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof statusBannerApiApiStatusBannerGet>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getStatusBannerApiApiStatusBannerGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Dashboard
 */
export const dashboardGet = (
  params?: DashboardGetParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.get(`https://builds.flathub.org/`, {
    ...options,
    params: { ...params, ...options?.params },
  })
}

export const getDashboardGetQueryKey = (params?: DashboardGetParams) => {
  return [`https://builds.flathub.org/`, ...(params ? [params] : [])] as const
}

export const getDashboardGetQueryOptions = <
  TData = Awaited<ReturnType<typeof dashboardGet>>,
  TError = AxiosError<void | HTTPValidationError>,
>(
  params?: DashboardGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dashboardGet>>, TError, TData>
    >
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getDashboardGetQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof dashboardGet>>> = ({
    signal,
  }) => dashboardGet(params, { signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof dashboardGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DashboardGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof dashboardGet>>
>
export type DashboardGetQueryError = AxiosError<void | HTTPValidationError>

export function useDashboardGet<
  TData = Awaited<ReturnType<typeof dashboardGet>>,
  TError = AxiosError<void | HTTPValidationError>,
>(
  params: undefined | DashboardGetParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dashboardGet>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dashboardGet>>,
          TError,
          Awaited<ReturnType<typeof dashboardGet>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useDashboardGet<
  TData = Awaited<ReturnType<typeof dashboardGet>>,
  TError = AxiosError<void | HTTPValidationError>,
>(
  params?: DashboardGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dashboardGet>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dashboardGet>>,
          TError,
          Awaited<ReturnType<typeof dashboardGet>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useDashboardGet<
  TData = Awaited<ReturnType<typeof dashboardGet>>,
  TError = AxiosError<void | HTTPValidationError>,
>(
  params?: DashboardGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dashboardGet>>, TError, TData>
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Dashboard
 */

export function useDashboardGet<
  TData = Awaited<ReturnType<typeof dashboardGet>>,
  TError = AxiosError<void | HTTPValidationError>,
>(
  params?: DashboardGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dashboardGet>>, TError, TData>
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getDashboardGetQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary App Status
 */
export const appStatusStatusAppIdGet = (
  appId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.get(`https://builds.flathub.org/status/${appId}`, options)
}

export const getAppStatusStatusAppIdGetQueryKey = (appId: string) => {
  return [`https://builds.flathub.org/status/${appId}`] as const
}

export const getAppStatusStatusAppIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof appStatusStatusAppIdGet>>,
  TError = AxiosError<void | HTTPValidationError>,
>(
  appId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof appStatusStatusAppIdGet>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getAppStatusStatusAppIdGetQueryKey(appId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof appStatusStatusAppIdGet>>
  > = ({ signal }) =>
    appStatusStatusAppIdGet(appId, { signal, ...axiosOptions })

  return {
    queryKey,
    queryFn,
    enabled: appId !== null && appId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof appStatusStatusAppIdGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AppStatusStatusAppIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof appStatusStatusAppIdGet>>
>
export type AppStatusStatusAppIdGetQueryError =
  AxiosError<void | HTTPValidationError>

export function useAppStatusStatusAppIdGet<
  TData = Awaited<ReturnType<typeof appStatusStatusAppIdGet>>,
  TError = AxiosError<void | HTTPValidationError>,
>(
  appId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof appStatusStatusAppIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appStatusStatusAppIdGet>>,
          TError,
          Awaited<ReturnType<typeof appStatusStatusAppIdGet>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAppStatusStatusAppIdGet<
  TData = Awaited<ReturnType<typeof appStatusStatusAppIdGet>>,
  TError = AxiosError<void | HTTPValidationError>,
>(
  appId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof appStatusStatusAppIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appStatusStatusAppIdGet>>,
          TError,
          Awaited<ReturnType<typeof appStatusStatusAppIdGet>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAppStatusStatusAppIdGet<
  TData = Awaited<ReturnType<typeof appStatusStatusAppIdGet>>,
  TError = AxiosError<void | HTTPValidationError>,
>(
  appId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof appStatusStatusAppIdGet>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary App Status
 */

export function useAppStatusStatusAppIdGet<
  TData = Awaited<ReturnType<typeof appStatusStatusAppIdGet>>,
  TError = AxiosError<void | HTTPValidationError>,
>(
  appId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof appStatusStatusAppIdGet>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getAppStatusStatusAppIdGetQueryOptions(appId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Reproducible Status
 */
export const reproducibleStatusReproducibleGet = (
  params?: ReproducibleStatusReproducibleGetParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.get(`https://builds.flathub.org/reproducible`, {
    ...options,
    params: { ...params, ...options?.params },
  })
}

export const getReproducibleStatusReproducibleGetQueryKey = (
  params?: ReproducibleStatusReproducibleGetParams,
) => {
  return [
    `https://builds.flathub.org/reproducible`,
    ...(params ? [params] : []),
  ] as const
}

export const getReproducibleStatusReproducibleGetQueryOptions = <
  TData = Awaited<ReturnType<typeof reproducibleStatusReproducibleGet>>,
  TError = AxiosError<void | HTTPValidationError>,
>(
  params?: ReproducibleStatusReproducibleGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof reproducibleStatusReproducibleGet>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getReproducibleStatusReproducibleGetQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof reproducibleStatusReproducibleGet>>
  > = ({ signal }) =>
    reproducibleStatusReproducibleGet(params, { signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof reproducibleStatusReproducibleGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReproducibleStatusReproducibleGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof reproducibleStatusReproducibleGet>>
>
export type ReproducibleStatusReproducibleGetQueryError =
  AxiosError<void | HTTPValidationError>

export function useReproducibleStatusReproducibleGet<
  TData = Awaited<ReturnType<typeof reproducibleStatusReproducibleGet>>,
  TError = AxiosError<void | HTTPValidationError>,
>(
  params: undefined | ReproducibleStatusReproducibleGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof reproducibleStatusReproducibleGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reproducibleStatusReproducibleGet>>,
          TError,
          Awaited<ReturnType<typeof reproducibleStatusReproducibleGet>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useReproducibleStatusReproducibleGet<
  TData = Awaited<ReturnType<typeof reproducibleStatusReproducibleGet>>,
  TError = AxiosError<void | HTTPValidationError>,
>(
  params?: ReproducibleStatusReproducibleGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof reproducibleStatusReproducibleGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reproducibleStatusReproducibleGet>>,
          TError,
          Awaited<ReturnType<typeof reproducibleStatusReproducibleGet>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useReproducibleStatusReproducibleGet<
  TData = Awaited<ReturnType<typeof reproducibleStatusReproducibleGet>>,
  TError = AxiosError<void | HTTPValidationError>,
>(
  params?: ReproducibleStatusReproducibleGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof reproducibleStatusReproducibleGet>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Reproducible Status
 */

export function useReproducibleStatusReproducibleGet<
  TData = Awaited<ReturnType<typeof reproducibleStatusReproducibleGet>>,
  TError = AxiosError<void | HTTPValidationError>,
>(
  params?: ReproducibleStatusReproducibleGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof reproducibleStatusReproducibleGet>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getReproducibleStatusReproducibleGetQueryOptions(
    params,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}
