/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { AppPickRecommendationLastTimeAppOfTheWeek } from "./appPickRecommendationLastTimeAppOfTheWeek"
import type { AppPickRecommendationLastTimeAppOfTheDay } from "./appPickRecommendationLastTimeAppOfTheDay"

export interface AppPickRecommendation {
  app_id: string
  numberOfTimesAppOfTheWeek: number
  lastTimeAppOfTheWeek: AppPickRecommendationLastTimeAppOfTheWeek
  numberOfTimesAppOfTheDay: number
  lastTimeAppOfTheDay: AppPickRecommendationLastTimeAppOfTheDay
}
