/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { Provides } from "./provides"

export type AppstreamResponseProvidesAnyOfItem = string | Provides
