/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */

export type AppSchemasSortBy =
  (typeof AppSchemasSortBy)[keyof typeof AppSchemasSortBy]

export const AppSchemasSortBy = {
  trending: "trending",
  installs_last_month: "installs_last_month",
} as const
