/* tslint:disable */
/* eslint-disable */
/**
 * Flathub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AvailableLoginMethodStatus } from "./available-login-method-status"
// May contain unused imports in some cases
// @ts-ignore
import { AvailableMethodType } from "./available-method-type"
// May contain unused imports in some cases
// @ts-ignore
import { LoginProvider } from "./login-provider"

/**
 *
 * @export
 * @interface AvailableMethod
 */
export interface AvailableMethod {
  /**
   *
   * @type {AvailableMethodType}
   * @memberof AvailableMethod
   */
  method: AvailableMethodType
  /**
   *
   * @type {string}
   * @memberof AvailableMethod
   */
  website?: string | null
  /**
   *
   * @type {string}
   * @memberof AvailableMethod
   */
  website_token?: string | null
  /**
   *
   * @type {LoginProvider}
   * @memberof AvailableMethod
   */
  login_provider?: LoginProvider | null
  /**
   *
   * @type {string}
   * @memberof AvailableMethod
   */
  login_name?: string | null
  /**
   *
   * @type {boolean}
   * @memberof AvailableMethod
   */
  login_is_organization?: boolean | null
  /**
   *
   * @type {AvailableLoginMethodStatus}
   * @memberof AvailableMethod
   */
  login_status?: AvailableLoginMethodStatus | null
}
