/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { AvailableLoginMethodStatus } from "./availableLoginMethodStatus"

export type AvailableMethodLoginStatus = AvailableLoginMethodStatus | null
