/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */

export type AvailableMethodType =
  (typeof AvailableMethodType)[keyof typeof AvailableMethodType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AvailableMethodType = {
  website: "website",
  login_provider: "login_provider",
} as const
