/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Branding color information.
 */
export interface Branding {
  value: string
  scheme_preference?: "light" | "dark" | null
  type: "primary"
}
