/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { BundleRuntime } from "./bundleRuntime"
import type { BundleSdk } from "./bundleSdk"

/**
 * Bundle information.
 */
export interface Bundle {
  value: string
  type: string
  runtime?: BundleRuntime
  sdk?: BundleSdk
}
