/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { _BuildCheck } from "./_buildCheck"
import type { CandidateAssessmentResponseAcceptanceBasis } from "./candidateAssessmentResponseAcceptanceBasis"
import type { CandidateAssessmentResponseBaselineId } from "./candidateAssessmentResponseBaselineId"
import type { CandidateAssessmentResponseCanonicalizationVersion } from "./candidateAssessmentResponseCanonicalizationVersion"
import type { CandidateAssessmentResponseDifferences } from "./candidateAssessmentResponseDifferences"
import type { CandidateAssessmentResponseErrorCode } from "./candidateAssessmentResponseErrorCode"
import type { CandidateAssessmentResponseErrorMessage } from "./candidateAssessmentResponseErrorMessage"
import type { CandidateAssessmentResponseLinkedAssessmentId } from "./candidateAssessmentResponseLinkedAssessmentId"
import type { CandidateAssessmentResponseLinkedFingerprintMatch } from "./candidateAssessmentResponseLinkedFingerprintMatch"
import type { CandidateAssessmentResponseOutcome } from "./candidateAssessmentResponseOutcome"
import type { CandidateAssessmentResponseSnapshotFingerprint } from "./candidateAssessmentResponseSnapshotFingerprint"
import type { CandidateIdentity } from "./candidateIdentity"

export interface CandidateAssessmentResponse {
  assessment_id: number
  candidate_identity: CandidateIdentity
  snapshot_fingerprint: CandidateAssessmentResponseSnapshotFingerprint
  outcome: CandidateAssessmentResponseOutcome
  acceptance_basis?: CandidateAssessmentResponseAcceptanceBasis
  baseline_id?: CandidateAssessmentResponseBaselineId
  /** @nullable */
  review_url?: null
  mode?: "observational"
  canonicalization_version?: CandidateAssessmentResponseCanonicalizationVersion
  assessment_identity: string
  expected_arches: string[]
  published_comparison_available: boolean
  differences: CandidateAssessmentResponseDifferences
  build_checks: _BuildCheck[]
  linked_assessment_id?: CandidateAssessmentResponseLinkedAssessmentId
  linked_fingerprint_match?: CandidateAssessmentResponseLinkedFingerprintMatch
  error_code?: CandidateAssessmentResponseErrorCode
  error_message?: CandidateAssessmentResponseErrorMessage
}
