/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { ContentRatingType } from "./contentRatingType"

/**
 * Content rating information.
 */
export interface ContentRating {
  type?: ContentRatingType
  [key: string]: unknown
}
