/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { AppSchemasSortBy } from "./appSchemasSortBy"

export type GetCategoryCollectionCategoryCategoryGetParams = {
  exclude_subcategories?: string[]
  page?: number | null
  per_page?: number | null
  locale?: string
  sort_by?: AppSchemasSortBy | null
}
