/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */

export type GetIsFreeSoftwarePurchasesStorefrontInfoIsFreeSoftwareGetParams = {
  app_id: string
  license?: string | null
}
