/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */

export interface Guideline {
  category: string
  id: string
  needed_to_pass_since: string
  read_only?: boolean
  url: string
}
