/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { AppMaintainer } from "./appMaintainer"
import type { ManagedAppResponseFirstSeenAt } from "./managedAppResponseFirstSeenAt"
import type { ManagedAppResponseScope } from "./managedAppResponseScope"

export interface ManagedAppResponse {
  app_id: string
  archived: boolean
  created_at: number
  first_seen_at: ManagedAppResponseFirstSeenAt
  maintainers: AppMaintainer[]
  scope: ManagedAppResponseScope
}
