/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */

export type ManifestChangeKind =
  (typeof ManifestChangeKind)[keyof typeof ManifestChangeKind]

export const ManifestChangeKind = {
  module_added: "module_added",
  module_removed: "module_removed",
  module_match_ambiguous: "module_match_ambiguous",
  source_type_changed: "source_type_changed",
  source_options_changed: "source_options_changed",
  source_order_changed: "source_order_changed",
  patch_or_script_added: "patch_or_script_added",
  buildsystem_changed: "buildsystem_changed",
  build_commands_changed: "build_commands_changed",
  post_install_changed: "post_install_changed",
  config_options_changed: "config_options_changed",
  build_options_changed: "build_options_changed",
  module_layout_changed: "module_layout_changed",
  top_level_cleanup_changed: "top_level_cleanup_changed",
  extensions_changed: "extensions_changed",
  runtime_id_changed: "runtime_id_changed",
  sdk_id_changed: "sdk_id_changed",
  application_command_changed: "application_command_changed",
  arch_selection_changed: "arch_selection_changed",
} as const
