/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */

export type MeilisearchResponseAppsIndexFacetDistributionAnyOf = {
  [key: string]: { [key: string]: number }
}
