/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */

export type MetadataFlathubVerificationMethod =
  | "manual"
  | "website"
  | "login_provider"
  | "none"
  | null
