/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { ManifestSourceOriginRequestData } from "./manifestSourceOriginRequestData"
import type { RequestData } from "./requestData"

export type ModerationRequestResponseRequestData =
  | RequestData
  | ManifestSourceOriginRequestData
  | null
