/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { MonthlyPermissionStatsResultPermissionValue } from "./monthlyPermissionStatsResultPermissionValue"

export interface MonthlyPermissionStatsResult {
  app_id: string
  month: string
  permission: string
  permission_value?: MonthlyPermissionStatsResultPermissionValue
  created_at: string
}
