/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */

export interface Pagination {
  page: number
  page_size: number
  total: number
  total_pages: number
}
