/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */

export interface PasskeyRenameRequest {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string
}
