/* tslint:disable */
/* eslint-disable */
/**
 * Flathub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PostTransactionResponse
 */
export interface PostTransactionResponse {
  /**
   *
   * @type {string}
   * @memberof PostTransactionResponse
   */
  status: string
  /**
   *
   * @type {string}
   * @memberof PostTransactionResponse
   */
  id: string
}
