/* tslint:disable */
/* eslint-disable */
/**
 * Flathub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { MinimumPayment } from "./minimum-payment"
// May contain unused imports in some cases
// @ts-ignore
import { RecommendedDonation } from "./recommended-donation"

/**
 *
 * @export
 * @interface PricingInfo
 */
export interface PricingInfo {
  /**
   *
   * @type {RecommendedDonation}
   * @memberof PricingInfo
   */
  recommended_donation: RecommendedDonation
  /**
   *
   * @type {MinimumPayment}
   * @memberof PricingInfo
   */
  minimum_payment: MinimumPayment
}
