/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { QualityModerationDashboardRowAppstreamAnyOf } from "./qualityModerationDashboardRowAppstreamAnyOf"

export type QualityModerationDashboardRowAppstream =
  QualityModerationDashboardRowAppstreamAnyOf | null
