/* tslint:disable */
/* eslint-disable */
/**
 * Flathub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { Comment } from "./comment"
// May contain unused imports in some cases
// @ts-ignore
import { Guideline } from "./guideline"
// May contain unused imports in some cases
// @ts-ignore
import { Passed } from "./passed"
// May contain unused imports in some cases
// @ts-ignore
import { UpdatedBy } from "./updated-by"

/**
 *
 * @export
 * @interface QualityModerationType
 */
export interface QualityModerationType {
  /**
   *
   * @type {string}
   * @memberof QualityModerationType
   */
  guideline_id: string
  /**
   *
   * @type {Guideline}
   * @memberof QualityModerationType
   */
  guideline: Guideline
  /**
   *
   * @type {string}
   * @memberof QualityModerationType
   */
  app_id: string
  /**
   *
   * @type {string}
   * @memberof QualityModerationType
   */
  updated_at: string
  /**
   *
   * @type {UpdatedBy}
   * @memberof QualityModerationType
   */
  updated_by: UpdatedBy
  /**
   *
   * @type {Passed}
   * @memberof QualityModerationType
   */
  passed: Passed
  /**
   *
   * @type {Comment}
   * @memberof QualityModerationType
   */
  comment: Comment
}
