/* tslint:disable */
/* eslint-disable */
/**
 * Flathub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { Pagination } from "./pagination"
// May contain unused imports in some cases
// @ts-ignore
import { QualityModerationDashboardRow } from "./quality-moderation-dashboard-row"

/**
 *
 * @export
 * @interface QualityModerationDashboardResponse
 */
export interface QualityModerationDashboardResponse {
  /**
   *
   * @type {Array<QualityModerationDashboardRow>}
   * @memberof QualityModerationDashboardResponse
   */
  apps: Array<QualityModerationDashboardRow>
  /**
   *
   * @type {Pagination}
   * @memberof QualityModerationDashboardResponse
   */
  pagination: Pagination
}
