/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { ReleaseVersion } from "./releaseVersion"
import type { ReleaseDescription } from "./releaseDescription"
import type { ReleaseUrl } from "./releaseUrl"

/**
 * A release/version entry.
 */
export interface Release {
  timestamp: string
  version?: ReleaseVersion
  description?: ReleaseDescription
  url?: ReleaseUrl
}
