/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { RequestDataKeys } from "./requestDataKeys"
import type { RequestDataCurrentValues } from "./requestDataCurrentValues"

export interface RequestData {
  keys: RequestDataKeys
  current_values: RequestDataCurrentValues
}
