/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { AppTypesJSONValueOutput } from "./appTypesJSONValueOutput"

export type RuntimeAppstreamContentRatingDetailsAnyOf = {
  [key: string]: AppTypesJSONValueOutput | null
}
