/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { ScreenshotCaption } from "./screenshotCaption"
import type { ScreenshotDefault } from "./screenshotDefault"
import type { ScreenshotSize } from "./screenshotSize"

/**
 * A screenshot with multiple size variants.
 */
export interface Screenshot {
  sizes: ScreenshotSize[]
  caption?: ScreenshotCaption
  default?: ScreenshotDefault
}
