/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { StorefrontInfoPricing } from "./storefrontInfoPricing"
import type { StorefrontInfoVerification } from "./storefrontInfoVerification"

export interface StorefrontInfo {
  is_free_software?: boolean
  pricing?: StorefrontInfoPricing
  verification?: StorefrontInfoVerification
}
