/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { SummaryPermissions } from "./summaryPermissions"

export type SummaryMetadataPermissions = SummaryPermissions | null
