/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { SwitchToDirectUploadRequestScope } from "./switchToDirectUploadRequestScope"

export interface SwitchToDirectUploadRequest {
  app_id: string
  primary_maintainer_user_id: number
  scope?: SwitchToDirectUploadRequestScope
}
