/* tslint:disable */
/* eslint-disable */
/**
 * Flathub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { IssuedTo } from "./issued-to"

/**
 *
 * @export
 * @interface TokenResponse
 */
export interface TokenResponse {
  /**
   *
   * @type {number}
   * @memberof TokenResponse
   */
  id: number
  /**
   *
   * @type {string}
   * @memberof TokenResponse
   */
  comment: string
  /**
   *
   * @type {string}
   * @memberof TokenResponse
   */
  app_id: string
  /**
   *
   * @type {Array<string>}
   * @memberof TokenResponse
   */
  scopes: Array<string>
  /**
   *
   * @type {Array<string>}
   * @memberof TokenResponse
   */
  repos: Array<string>
  /**
   *
   * @type {number}
   * @memberof TokenResponse
   */
  issued_at: number
  /**
   *
   * @type {IssuedTo}
   * @memberof TokenResponse
   */
  issued_to: IssuedTo
  /**
   *
   * @type {number}
   * @memberof TokenResponse
   */
  expires_at: number
  /**
   *
   * @type {boolean}
   * @memberof TokenResponse
   */
  revoked: boolean
}
