/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { TokenResponseIssuedTo } from "./tokenResponseIssuedTo"

export interface TokenResponse {
  app_id: string
  comment: string
  expires_at: number
  id: number
  issued_at: number
  issued_to: TokenResponseIssuedTo
  repos: string[]
  revoked: boolean
  scopes: string[]
}
