/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Translation information.
 */
export interface Translation {
  value?: string | null
  type?: string | null
}
