/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { TransactionCard } from "./transactionCard"
import type { TransactionRow } from "./transactionRow"
import type { TransactionReceipt } from "./transactionReceipt"
import type { TransactionSummary } from "./transactionSummary"

export interface Transaction {
  card?: TransactionCard
  details: TransactionRow[]
  receipt?: TransactionReceipt
  summary: TransactionSummary
}
