/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */

export interface TrendingCategory {
  category: string
  current_year_downloads: number
  previous_year_downloads: number
  growth: number
  growth_percentage: number
}
