/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateRuntimeRequestExtraIds } from "./updateRuntimeRequestExtraIds"
import type { UpdateRuntimeRequestPrefixes } from "./updateRuntimeRequestPrefixes"
import type { UpdateRuntimeRequestRepos } from "./updateRuntimeRequestRepos"

export interface UpdateRuntimeRequest {
  prefixes?: UpdateRuntimeRequestPrefixes
  extra_ids?: UpdateRuntimeRequestExtraIds
  repos?: UpdateRuntimeRequestRepos
}
