/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { EmailAccountResult } from "./emailAccountResult"
import type { GithubAccountResult } from "./githubAccountResult"
import type { GitlabAccountResult } from "./gitlabAccountResult"
import type { GnomeAccountResult } from "./gnomeAccountResult"
import type { GoogleAccountResult } from "./googleAccountResult"
import type { KdeAccountResult } from "./kdeAccountResult"

export type UserResultDefaultAccount =
  | GithubAccountResult
  | GitlabAccountResult
  | GnomeAccountResult
  | GoogleAccountResult
  | KdeAccountResult
  | EmailAccountResult
  | null
