/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { VendingConfigPlatforms } from "./vendingConfigPlatforms"

/**
 * Global vending environment configuration values
 */
export interface VendingConfig {
  status: "ok"
  platforms: VendingConfigPlatforms
  fee_fixed_cost: number
  fee_cost_percent: number
  fee_prefer_percent: number
}
