/* tslint:disable */
/* eslint-disable */
/**
 * Flathub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *      The status object says whether the user is capable of receiving payments,     and also whether or not there are pending onboarding operations to complete
 * @export
 * @interface VendingStatus
 */
export interface VendingStatus {
  /**
   *
   * @type {string}
   * @memberof VendingStatus
   */
  status: string
  /**
   *
   * @type {boolean}
   * @memberof VendingStatus
   */
  can_take_payments: boolean
  /**
   *
   * @type {boolean}
   * @memberof VendingStatus
   */
  needs_attention: boolean
  /**
   *
   * @type {boolean}
   * @memberof VendingStatus
   */
  details_submitted: boolean
}
