/* tslint:disable */
/* eslint-disable */
/**
 * Flathub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Any redirect the vending system needs to create will be returned like this.  Status will be \"ok\" otherwise you cannot rely on target_url and instead something look for like error.
 * @export
 * @interface VendingRedirect
 */
export interface VendingRedirect {
  /**
   *
   * @type {string}
   * @memberof VendingRedirect
   */
  status: string
  /**
   *
   * @type {string}
   * @memberof VendingRedirect
   */
  target_url: string
}
