/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Any redirect the vending system needs to create will be returned like this.

Status will be "ok" otherwise you cannot rely on target_url and instead
something look for like error.
 */
export interface VendingRedirect {
  status: string
  target_url: string
}
