/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { LoginProvider } from "./loginProvider"

export interface VerificationStatusLoginProvider {
  verified: true
  timestamp: string
  method: "login_provider"
  login_provider: LoginProvider
  login_name: string
  detail?: string | null
  login_is_organization?: boolean | null
}
