/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import type { ErrorDetail } from "./errorDetail"

export interface WebsiteVerificationResult {
  verified: boolean
  detail?: ErrorDetail | null
  status_code?: number | null
}
