/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */

export interface YearInReviewCategoryGrowthApp {
  category: string
  app_id: string
  name: string
  icon: string
  summary: string
  growth: number
  growth_percentage: number
}
