version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "react-is"
          - "@types/react"
      storybook:
        patterns:
          - "@storybook/*"
          - storybook
      embla:
        patterns:
          - embla

  - package-ecosystem: "npm"
    directory: "/backend-node"
    schedule:
      interval: "daily"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
      react-email:
        patterns:
          - "@react-email/*"
          - "react-email"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: "uv"
    directory: "/backend"
    schedule:
      interval: "weekly"
