/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: process.env.NEXT_PUBLIC_SITE_BASE_URI || "https://flathub.org",
  alternateRefs: [
    {
      href: "https://flathub.org",
      hreflang: "en",
    },
    ...[
      "en",
      "en-GB",
      "de",
      "fr",
      "nb-NO",
      "tr",
      "fi",
      "id",
      "pl",
      "pt-BR",
      "it",
      "ru",
      "si",
      "vi",
      "ar",
      "es",
      "ja",
      "cs",
      "zh-Hans",
      "bg",
      "uk",
      "et",
      "ca",
      "el",
      "ta",
      "fa",
      "hi",
      "bn",
      "eo",
      "lt",
      "hr",
      "be",
      "hu",
      "nl",
      "pt",
      "zh-Hant",
      "oc",
      "da",
      "az",
      "he",
      "ro",
      "hy",
      "ko",
      "sv",
      "pa",
      "sq",
      "ia",
      "ckb",
      "ga",
      "kab",
      "fil",
      "br",
    ].map((language) => ({
      href: `https://flathub.org/${language}`,
      hreflang: language,
    })),
  ],
  generateRobotsTxt: true,
  exclude: ["/server-sitemap-index.xml"],
  robotsTxtOptions: {
    policies: [
      {
        userAgent: "GPTBot",
        disallow: ["/"],
      },
      {
        userAgent: "CCBot",
        disallow: ["/"],
      },
      {
        userAgent: "Google-Extended",
        disallow: ["/"],
      },
      {
        userAgent: "anthropic-ai",
        disallow: ["/"],
      },
      {
        userAgent: "Omgilibot",
        disallow: ["/"],
      },
      {
        userAgent: "Omgili",
        disallow: ["/"],
      },
      {
        userAgent: "FacebookBot",
        disallow: ["/"],
      },
    ],
    additionalSitemaps: [
      `${process.env.NEXT_PUBLIC_SITE_BASE_URI}/server-sitemap-index.xml`,
    ],
  },
}
