/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import { HttpResponse, http } from "msw"
import type { RequestHandlerOptions } from "msw"

export const getOpenidConfigurationWellKnownOpenidConfigurationGetMockHandler =
  (
    overrideResponse?:
      | unknown
      | ((
          info: Parameters<Parameters<typeof http.get>[1]>[0],
        ) => Promise<unknown> | unknown),
    options?: RequestHandlerOptions,
  ) => {
    return http.get(
      "*/.well-known/openid-configuration",
      async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
        if (typeof overrideResponse === "function") {
          await overrideResponse(info)
        }

        return new HttpResponse(null, { status: 200 })
      },
      options,
    )
  }

export const getJwksOidcJwksJsonGetMockHandler = (
  overrideResponse?:
    | unknown
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<unknown> | unknown),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/oidc/jwks.json",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info)
      }

      return new HttpResponse(null, { status: 200 })
    },
    options,
  )
}

export const getAuthorizeOidcAuthorizeGetMockHandler = (
  overrideResponse?:
    | unknown
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<unknown> | unknown),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/oidc/authorize",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info)
      }

      return new HttpResponse(null, { status: 200 })
    },
    options,
  )
}

export const getTokenOidcTokenPostMockHandler = (
  overrideResponse?:
    | unknown
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<unknown> | unknown),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/oidc/token",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info)
      }

      return new HttpResponse(null, { status: 200 })
    },
    options,
  )
}

export const getUserinfoOidcUserinfoGetMockHandler = (
  overrideResponse?:
    | unknown
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<unknown> | unknown),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/oidc/userinfo",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info)
      }

      return new HttpResponse(null, { status: 200 })
    },
    options,
  )
}
export const getOidcMock = () => [
  getOpenidConfigurationWellKnownOpenidConfigurationGetMockHandler(),
  getJwksOidcJwksJsonGetMockHandler(),
  getAuthorizeOidcAuthorizeGetMockHandler(),
  getTokenOidcTokenPostMockHandler(),
  getUserinfoOidcUserinfoGetMockHandler(),
]
