/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import { HttpResponse, http } from "msw"
import type { RequestHandlerOptions } from "msw"

export const getHealthcheckStatusGetMockHandler = (
  overrideResponse?:
    | unknown
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<unknown> | unknown),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/status",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info)
      }

      return new HttpResponse(null, { status: 200 })
    },
    options,
  )
}
export const getHealthcheckMock = () => [getHealthcheckStatusGetMockHandler()]
