/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/react-query"
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import axios from "axios"
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios"

/**
 * @summary Healthcheck
 */
export const healthcheckStatusGet = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.get(`/status`, options)
}

export const getHealthcheckStatusGetQueryKey = () => {
  return [`/status`] as const
}

export const getHealthcheckStatusGetQueryOptions = <
  TData = Awaited<ReturnType<typeof healthcheckStatusGet>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof healthcheckStatusGet>>,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getHealthcheckStatusGetQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof healthcheckStatusGet>>
  > = ({ signal }) => healthcheckStatusGet({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthcheckStatusGet>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type HealthcheckStatusGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthcheckStatusGet>>
>
export type HealthcheckStatusGetQueryError = AxiosError<unknown>

/**
 * @summary Healthcheck
 */
export const useHealthcheckStatusGet = <
  TData = Awaited<ReturnType<typeof healthcheckStatusGet>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof healthcheckStatusGet>>,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getHealthcheckStatusGetQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  query.queryKey = queryOptions.queryKey

  return query
}
