/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/react-query"
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import axios from "axios"
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios"
import type {
  GetAppsCompatAppsGet200,
  GetAppsInCategoryCompatAppsCategoryCategoryGet200,
  GetPopularAppsCompatAppsCollectionPopular50Get200,
  GetPopularAppsCompatAppsCollectionPopularGet200,
  GetRecentlyAddedCompatAppsCollectionNew50Get200,
  GetRecentlyAddedCompatAppsCollectionNewGet200,
  GetRecentlyUpdatedCompatAppsCollectionRecentlyUpdated50Get200,
  GetRecentlyUpdatedCompatAppsCollectionRecentlyUpdatedGet200,
  GetSearchCompatAppsSearchQueryGet200,
  GetSingleAppCompatAppsAppIdGet200,
  HTTPValidationError,
} from ".././model"

/**
 * @summary Get Apps
 */
export const getAppsCompatAppsGet = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetAppsCompatAppsGet200>> => {
  return axios.get(`/compat/apps`, options)
}

export const getGetAppsCompatAppsGetQueryKey = () => {
  return [`/compat/apps`] as const
}

export const getGetAppsCompatAppsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getAppsCompatAppsGet>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAppsCompatAppsGet>>,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAppsCompatAppsGetQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAppsCompatAppsGet>>
  > = ({ signal }) => getAppsCompatAppsGet({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAppsCompatAppsGet>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetAppsCompatAppsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAppsCompatAppsGet>>
>
export type GetAppsCompatAppsGetQueryError = AxiosError<unknown>

/**
 * @summary Get Apps
 */
export const useGetAppsCompatAppsGet = <
  TData = Awaited<ReturnType<typeof getAppsCompatAppsGet>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAppsCompatAppsGet>>,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetAppsCompatAppsGetQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Get Apps In Category
 */
export const getAppsInCategoryCompatAppsCategoryCategoryGet = (
  category: string,
  options?: AxiosRequestConfig,
): Promise<
  AxiosResponse<GetAppsInCategoryCompatAppsCategoryCategoryGet200>
> => {
  return axios.get(`/compat/apps/category/${category}`, options)
}

export const getGetAppsInCategoryCompatAppsCategoryCategoryGetQueryKey = (
  category: string,
) => {
  return [`/compat/apps/category/${category}`] as const
}

export const getGetAppsInCategoryCompatAppsCategoryCategoryGetQueryOptions = <
  TData = Awaited<
    ReturnType<typeof getAppsInCategoryCompatAppsCategoryCategoryGet>
  >,
  TError = AxiosError<HTTPValidationError>,
>(
  category: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getAppsInCategoryCompatAppsCategoryCategoryGet>
        >,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetAppsInCategoryCompatAppsCategoryCategoryGetQueryKey(category)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAppsInCategoryCompatAppsCategoryCategoryGet>>
  > = ({ signal }) =>
    getAppsInCategoryCompatAppsCategoryCategoryGet(category, {
      signal,
      ...axiosOptions,
    })

  return {
    queryKey,
    queryFn,
    enabled: !!category,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAppsInCategoryCompatAppsCategoryCategoryGet>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetAppsInCategoryCompatAppsCategoryCategoryGetQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof getAppsInCategoryCompatAppsCategoryCategoryGet>>
  >
export type GetAppsInCategoryCompatAppsCategoryCategoryGetQueryError =
  AxiosError<HTTPValidationError>

/**
 * @summary Get Apps In Category
 */
export const useGetAppsInCategoryCompatAppsCategoryCategoryGet = <
  TData = Awaited<
    ReturnType<typeof getAppsInCategoryCompatAppsCategoryCategoryGet>
  >,
  TError = AxiosError<HTTPValidationError>,
>(
  category: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getAppsInCategoryCompatAppsCategoryCategoryGet>
        >,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getGetAppsInCategoryCompatAppsCategoryCategoryGetQueryOptions(
      category,
      options,
    )

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Get Recently Updated
 */
export const getRecentlyUpdatedCompatAppsCollectionRecentlyUpdated50Get = (
  options?: AxiosRequestConfig,
): Promise<
  AxiosResponse<GetRecentlyUpdatedCompatAppsCollectionRecentlyUpdated50Get200>
> => {
  return axios.get(`/compat/apps/collection/recently-updated/50`, options)
}

export const getGetRecentlyUpdatedCompatAppsCollectionRecentlyUpdated50GetQueryKey =
  () => {
    return [`/compat/apps/collection/recently-updated/50`] as const
  }

export const getGetRecentlyUpdatedCompatAppsCollectionRecentlyUpdated50GetQueryOptions =
  <
    TData = Awaited<
      ReturnType<
        typeof getRecentlyUpdatedCompatAppsCollectionRecentlyUpdated50Get
      >
    >,
    TError = AxiosError<unknown>,
  >(options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof getRecentlyUpdatedCompatAppsCollectionRecentlyUpdated50Get
          >
        >,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  }) => {
    const { query: queryOptions, axios: axiosOptions } = options ?? {}

    const queryKey =
      queryOptions?.queryKey ??
      getGetRecentlyUpdatedCompatAppsCollectionRecentlyUpdated50GetQueryKey()

    const queryFn: QueryFunction<
      Awaited<
        ReturnType<
          typeof getRecentlyUpdatedCompatAppsCollectionRecentlyUpdated50Get
        >
      >
    > = ({ signal }) =>
      getRecentlyUpdatedCompatAppsCollectionRecentlyUpdated50Get({
        signal,
        ...axiosOptions,
      })

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
      Awaited<
        ReturnType<
          typeof getRecentlyUpdatedCompatAppsCollectionRecentlyUpdated50Get
        >
      >,
      TError,
      TData
    > & { queryKey: QueryKey }
  }

export type GetRecentlyUpdatedCompatAppsCollectionRecentlyUpdated50GetQueryResult =
  NonNullable<
    Awaited<
      ReturnType<
        typeof getRecentlyUpdatedCompatAppsCollectionRecentlyUpdated50Get
      >
    >
  >
export type GetRecentlyUpdatedCompatAppsCollectionRecentlyUpdated50GetQueryError =
  AxiosError<unknown>

/**
 * @summary Get Recently Updated
 */
export const useGetRecentlyUpdatedCompatAppsCollectionRecentlyUpdated50Get = <
  TData = Awaited<
    ReturnType<
      typeof getRecentlyUpdatedCompatAppsCollectionRecentlyUpdated50Get
    >
  >,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<
        ReturnType<
          typeof getRecentlyUpdatedCompatAppsCollectionRecentlyUpdated50Get
        >
      >,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getGetRecentlyUpdatedCompatAppsCollectionRecentlyUpdated50GetQueryOptions(
      options,
    )

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Get Recently Updated
 */
export const getRecentlyUpdatedCompatAppsCollectionRecentlyUpdatedGet = (
  options?: AxiosRequestConfig,
): Promise<
  AxiosResponse<GetRecentlyUpdatedCompatAppsCollectionRecentlyUpdatedGet200>
> => {
  return axios.get(`/compat/apps/collection/recently-updated`, options)
}

export const getGetRecentlyUpdatedCompatAppsCollectionRecentlyUpdatedGetQueryKey =
  () => {
    return [`/compat/apps/collection/recently-updated`] as const
  }

export const getGetRecentlyUpdatedCompatAppsCollectionRecentlyUpdatedGetQueryOptions =
  <
    TData = Awaited<
      ReturnType<
        typeof getRecentlyUpdatedCompatAppsCollectionRecentlyUpdatedGet
      >
    >,
    TError = AxiosError<unknown>,
  >(options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof getRecentlyUpdatedCompatAppsCollectionRecentlyUpdatedGet
          >
        >,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  }) => {
    const { query: queryOptions, axios: axiosOptions } = options ?? {}

    const queryKey =
      queryOptions?.queryKey ??
      getGetRecentlyUpdatedCompatAppsCollectionRecentlyUpdatedGetQueryKey()

    const queryFn: QueryFunction<
      Awaited<
        ReturnType<
          typeof getRecentlyUpdatedCompatAppsCollectionRecentlyUpdatedGet
        >
      >
    > = ({ signal }) =>
      getRecentlyUpdatedCompatAppsCollectionRecentlyUpdatedGet({
        signal,
        ...axiosOptions,
      })

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
      Awaited<
        ReturnType<
          typeof getRecentlyUpdatedCompatAppsCollectionRecentlyUpdatedGet
        >
      >,
      TError,
      TData
    > & { queryKey: QueryKey }
  }

export type GetRecentlyUpdatedCompatAppsCollectionRecentlyUpdatedGetQueryResult =
  NonNullable<
    Awaited<
      ReturnType<
        typeof getRecentlyUpdatedCompatAppsCollectionRecentlyUpdatedGet
      >
    >
  >
export type GetRecentlyUpdatedCompatAppsCollectionRecentlyUpdatedGetQueryError =
  AxiosError<unknown>

/**
 * @summary Get Recently Updated
 */
export const useGetRecentlyUpdatedCompatAppsCollectionRecentlyUpdatedGet = <
  TData = Awaited<
    ReturnType<typeof getRecentlyUpdatedCompatAppsCollectionRecentlyUpdatedGet>
  >,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<
        ReturnType<
          typeof getRecentlyUpdatedCompatAppsCollectionRecentlyUpdatedGet
        >
      >,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getGetRecentlyUpdatedCompatAppsCollectionRecentlyUpdatedGetQueryOptions(
      options,
    )

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Get Recently Added
 */
export const getRecentlyAddedCompatAppsCollectionNew50Get = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetRecentlyAddedCompatAppsCollectionNew50Get200>> => {
  return axios.get(`/compat/apps/collection/new/50`, options)
}

export const getGetRecentlyAddedCompatAppsCollectionNew50GetQueryKey = () => {
  return [`/compat/apps/collection/new/50`] as const
}

export const getGetRecentlyAddedCompatAppsCollectionNew50GetQueryOptions = <
  TData = Awaited<
    ReturnType<typeof getRecentlyAddedCompatAppsCollectionNew50Get>
  >,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getRecentlyAddedCompatAppsCollectionNew50Get>>,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetRecentlyAddedCompatAppsCollectionNew50GetQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getRecentlyAddedCompatAppsCollectionNew50Get>>
  > = ({ signal }) =>
    getRecentlyAddedCompatAppsCollectionNew50Get({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRecentlyAddedCompatAppsCollectionNew50Get>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetRecentlyAddedCompatAppsCollectionNew50GetQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof getRecentlyAddedCompatAppsCollectionNew50Get>>
  >
export type GetRecentlyAddedCompatAppsCollectionNew50GetQueryError =
  AxiosError<unknown>

/**
 * @summary Get Recently Added
 */
export const useGetRecentlyAddedCompatAppsCollectionNew50Get = <
  TData = Awaited<
    ReturnType<typeof getRecentlyAddedCompatAppsCollectionNew50Get>
  >,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getRecentlyAddedCompatAppsCollectionNew50Get>>,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getGetRecentlyAddedCompatAppsCollectionNew50GetQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Get Recently Added
 */
export const getRecentlyAddedCompatAppsCollectionNewGet = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetRecentlyAddedCompatAppsCollectionNewGet200>> => {
  return axios.get(`/compat/apps/collection/new`, options)
}

export const getGetRecentlyAddedCompatAppsCollectionNewGetQueryKey = () => {
  return [`/compat/apps/collection/new`] as const
}

export const getGetRecentlyAddedCompatAppsCollectionNewGetQueryOptions = <
  TData = Awaited<
    ReturnType<typeof getRecentlyAddedCompatAppsCollectionNewGet>
  >,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getRecentlyAddedCompatAppsCollectionNewGet>>,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetRecentlyAddedCompatAppsCollectionNewGetQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getRecentlyAddedCompatAppsCollectionNewGet>>
  > = ({ signal }) =>
    getRecentlyAddedCompatAppsCollectionNewGet({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRecentlyAddedCompatAppsCollectionNewGet>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetRecentlyAddedCompatAppsCollectionNewGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRecentlyAddedCompatAppsCollectionNewGet>>
>
export type GetRecentlyAddedCompatAppsCollectionNewGetQueryError =
  AxiosError<unknown>

/**
 * @summary Get Recently Added
 */
export const useGetRecentlyAddedCompatAppsCollectionNewGet = <
  TData = Awaited<
    ReturnType<typeof getRecentlyAddedCompatAppsCollectionNewGet>
  >,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getRecentlyAddedCompatAppsCollectionNewGet>>,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getGetRecentlyAddedCompatAppsCollectionNewGetQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Get Popular Apps
 */
export const getPopularAppsCompatAppsCollectionPopular50Get = (
  options?: AxiosRequestConfig,
): Promise<
  AxiosResponse<GetPopularAppsCompatAppsCollectionPopular50Get200>
> => {
  return axios.get(`/compat/apps/collection/popular/50`, options)
}

export const getGetPopularAppsCompatAppsCollectionPopular50GetQueryKey = () => {
  return [`/compat/apps/collection/popular/50`] as const
}

export const getGetPopularAppsCompatAppsCollectionPopular50GetQueryOptions = <
  TData = Awaited<
    ReturnType<typeof getPopularAppsCompatAppsCollectionPopular50Get>
  >,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<
        ReturnType<typeof getPopularAppsCompatAppsCollectionPopular50Get>
      >,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetPopularAppsCompatAppsCollectionPopular50GetQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPopularAppsCompatAppsCollectionPopular50Get>>
  > = ({ signal }) =>
    getPopularAppsCompatAppsCollectionPopular50Get({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPopularAppsCompatAppsCollectionPopular50Get>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetPopularAppsCompatAppsCollectionPopular50GetQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof getPopularAppsCompatAppsCollectionPopular50Get>>
  >
export type GetPopularAppsCompatAppsCollectionPopular50GetQueryError =
  AxiosError<unknown>

/**
 * @summary Get Popular Apps
 */
export const useGetPopularAppsCompatAppsCollectionPopular50Get = <
  TData = Awaited<
    ReturnType<typeof getPopularAppsCompatAppsCollectionPopular50Get>
  >,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<
        ReturnType<typeof getPopularAppsCompatAppsCollectionPopular50Get>
      >,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getGetPopularAppsCompatAppsCollectionPopular50GetQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Get Popular Apps
 */
export const getPopularAppsCompatAppsCollectionPopularGet = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetPopularAppsCompatAppsCollectionPopularGet200>> => {
  return axios.get(`/compat/apps/collection/popular`, options)
}

export const getGetPopularAppsCompatAppsCollectionPopularGetQueryKey = () => {
  return [`/compat/apps/collection/popular`] as const
}

export const getGetPopularAppsCompatAppsCollectionPopularGetQueryOptions = <
  TData = Awaited<
    ReturnType<typeof getPopularAppsCompatAppsCollectionPopularGet>
  >,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getPopularAppsCompatAppsCollectionPopularGet>>,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetPopularAppsCompatAppsCollectionPopularGetQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPopularAppsCompatAppsCollectionPopularGet>>
  > = ({ signal }) =>
    getPopularAppsCompatAppsCollectionPopularGet({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPopularAppsCompatAppsCollectionPopularGet>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetPopularAppsCompatAppsCollectionPopularGetQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof getPopularAppsCompatAppsCollectionPopularGet>>
  >
export type GetPopularAppsCompatAppsCollectionPopularGetQueryError =
  AxiosError<unknown>

/**
 * @summary Get Popular Apps
 */
export const useGetPopularAppsCompatAppsCollectionPopularGet = <
  TData = Awaited<
    ReturnType<typeof getPopularAppsCompatAppsCollectionPopularGet>
  >,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getPopularAppsCompatAppsCollectionPopularGet>>,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getGetPopularAppsCompatAppsCollectionPopularGetQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Get Search
 */
export const getSearchCompatAppsSearchQueryGet = (
  query: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetSearchCompatAppsSearchQueryGet200>> => {
  return axios.get(`/compat/apps/search/${query}`, options)
}

export const getGetSearchCompatAppsSearchQueryGetQueryKey = (query: string) => {
  return [`/compat/apps/search/${query}`] as const
}

export const getGetSearchCompatAppsSearchQueryGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getSearchCompatAppsSearchQueryGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  query: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSearchCompatAppsSearchQueryGet>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetSearchCompatAppsSearchQueryGetQueryKey(query)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSearchCompatAppsSearchQueryGet>>
  > = ({ signal }) =>
    getSearchCompatAppsSearchQueryGet(query, { signal, ...axiosOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!query,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getSearchCompatAppsSearchQueryGet>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetSearchCompatAppsSearchQueryGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSearchCompatAppsSearchQueryGet>>
>
export type GetSearchCompatAppsSearchQueryGetQueryError =
  AxiosError<HTTPValidationError>

/**
 * @summary Get Search
 */
export const useGetSearchCompatAppsSearchQueryGet = <
  TData = Awaited<ReturnType<typeof getSearchCompatAppsSearchQueryGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  query: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSearchCompatAppsSearchQueryGet>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetSearchCompatAppsSearchQueryGetQueryOptions(
    query,
    options,
  )

  const _query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  _query.queryKey = queryOptions.queryKey

  return _query
}

/**
 * @summary Get Single App
 */
export const getSingleAppCompatAppsAppIdGet = (
  appId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetSingleAppCompatAppsAppIdGet200>> => {
  return axios.get(`/compat/apps/${appId}`, options)
}

export const getGetSingleAppCompatAppsAppIdGetQueryKey = (appId: string) => {
  return [`/compat/apps/${appId}`] as const
}

export const getGetSingleAppCompatAppsAppIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getSingleAppCompatAppsAppIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  appId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSingleAppCompatAppsAppIdGet>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetSingleAppCompatAppsAppIdGetQueryKey(appId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSingleAppCompatAppsAppIdGet>>
  > = ({ signal }) =>
    getSingleAppCompatAppsAppIdGet(appId, { signal, ...axiosOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!appId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getSingleAppCompatAppsAppIdGet>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetSingleAppCompatAppsAppIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSingleAppCompatAppsAppIdGet>>
>
export type GetSingleAppCompatAppsAppIdGetQueryError =
  AxiosError<HTTPValidationError>

/**
 * @summary Get Single App
 */
export const useGetSingleAppCompatAppsAppIdGet = <
  TData = Awaited<ReturnType<typeof getSingleAppCompatAppsAppIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  appId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSingleAppCompatAppsAppIdGet>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetSingleAppCompatAppsAppIdGetQueryOptions(
    appId,
    options,
  )

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  query.queryKey = queryOptions.queryKey

  return query
}
