/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import { HttpResponse, delay, http } from "msw"

export const getGetRecentlyUpdatedAppsFeedFeedRecentlyUpdatedGetMockHandler =
  () => {
    return http.get("*/feed/recently-updated", async () => {
      await delay(1000)
      return new HttpResponse(null, {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      })
    })
  }

export const getGetNewAppsFeedFeedNewGetMockHandler = () => {
  return http.get("*/feed/new", async () => {
    await delay(1000)
    return new HttpResponse(null, {
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
    })
  })
}

export const getGetRecentlyUpdatedAppsFeedPostgresFeedRecentlyUpdatedPostgresGetMockHandler =
  () => {
    return http.get("*/feed/recently-updated-postgres", async () => {
      await delay(1000)
      return new HttpResponse(null, {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      })
    })
  }

export const getGetNewAppsFeedPostgresFeedNewPostgresGetMockHandler = () => {
  return http.get("*/feed/new-postgres", async () => {
    await delay(1000)
    return new HttpResponse(null, {
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
    })
  })
}
export const getFeedMock = () => [
  getGetRecentlyUpdatedAppsFeedFeedRecentlyUpdatedGetMockHandler(),
  getGetNewAppsFeedFeedNewGetMockHandler(),
  getGetRecentlyUpdatedAppsFeedPostgresFeedRecentlyUpdatedPostgresGetMockHandler(),
  getGetNewAppsFeedPostgresFeedNewPostgresGetMockHandler(),
]
