/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import { faker } from "@faker-js/faker"
import { HttpResponse, delay, http } from "msw"
import type {
  ContinueGithubFlowAuthLoginGithubPost200,
  ContinueGitlabFlowAuthLoginGitlabPost200,
  ContinueGnomeFlowAuthLoginGnomePost200,
  ContinueGoogleFlowAuthLoginGooglePost200,
  ContinueKdeFlowAuthLoginKdePost200,
  DeleteUserResult,
  DoAgreeToPublisherAgreementAuthAcceptPublisherAgreementPost200,
  DoLogoutAuthLogoutPost200,
  GetDeleteUserResult,
  LoginMethod,
  RefreshDevFlatpaksReturn,
  StartGithubFlowAuthLoginGithubGet200,
  StartGitlabFlowAuthLoginGitlabGet200,
  StartGnomeFlowAuthLoginGnomeGet200,
  StartKdeFlowAuthLoginKdeGet200,
  UserInfo,
} from ".././model"

export const getGetLoginMethodsAuthLoginGetResponseMock = (
  overrideResponse: any = {},
): LoginMethod[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    method: faker.word.sample(),
    name: faker.word.sample(),
    ...overrideResponse,
  }))

export const getStartGithubFlowAuthLoginGithubGetResponseMock =
  (): StartGithubFlowAuthLoginGithubGet200 => ({})

export const getContinueGithubFlowAuthLoginGithubPostResponseMock =
  (): ContinueGithubFlowAuthLoginGithubPost200 => ({})

export const getStartGitlabFlowAuthLoginGitlabGetResponseMock =
  (): StartGitlabFlowAuthLoginGitlabGet200 => ({})

export const getContinueGitlabFlowAuthLoginGitlabPostResponseMock =
  (): ContinueGitlabFlowAuthLoginGitlabPost200 => ({})

export const getStartGnomeFlowAuthLoginGnomeGetResponseMock =
  (): StartGnomeFlowAuthLoginGnomeGet200 => ({})

export const getContinueGnomeFlowAuthLoginGnomePostResponseMock =
  (): ContinueGnomeFlowAuthLoginGnomePost200 => ({})

export const getStartKdeFlowAuthLoginKdeGetResponseMock =
  (): StartKdeFlowAuthLoginKdeGet200 => ({})

export const getContinueKdeFlowAuthLoginKdePostResponseMock =
  (): ContinueKdeFlowAuthLoginKdePost200 => ({})

export const getContinueGoogleFlowAuthLoginGooglePostResponseMock =
  (): ContinueGoogleFlowAuthLoginGooglePost200 => ({})

export const getGetUserinfoAuthUserinfoGetResponseMock = (
  overrideResponse: any = {},
): UserInfo => ({
  accepted_publisher_agreement_at: faker.helpers.arrayElement([
    `${faker.date.past().toISOString().split(".")[0]}Z`,
    {},
  ]),
  auths: {
    github: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        {
          avatar: faker.helpers.arrayElement([
            faker.helpers.arrayElement([faker.word.sample(), {}]),
            undefined,
          ]),
          login: faker.word.sample(),
          ...overrideResponse,
        },
        {},
      ]),
      undefined,
    ]),
    gitlab: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        {
          avatar: faker.helpers.arrayElement([
            faker.helpers.arrayElement([faker.word.sample(), {}]),
            undefined,
          ]),
          login: faker.word.sample(),
          ...overrideResponse,
        },
        {},
      ]),
      undefined,
    ]),
    gnome: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        {
          avatar: faker.helpers.arrayElement([
            faker.helpers.arrayElement([faker.word.sample(), {}]),
            undefined,
          ]),
          login: faker.word.sample(),
          ...overrideResponse,
        },
        {},
      ]),
      undefined,
    ]),
    kde: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        {
          avatar: faker.helpers.arrayElement([
            faker.helpers.arrayElement([faker.word.sample(), {}]),
            undefined,
          ]),
          login: faker.word.sample(),
          ...overrideResponse,
        },
        {},
      ]),
      undefined,
    ]),
    ...overrideResponse,
  },
  default_account: {
    avatar: faker.helpers.arrayElement([
      faker.helpers.arrayElement([faker.word.sample(), {}]),
      undefined,
    ]),
    login: faker.word.sample(),
    ...overrideResponse,
  },
  dev_flatpaks: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => faker.word.sample()),
    undefined,
  ]),
  displayname: faker.helpers.arrayElement([
    faker.helpers.arrayElement([faker.word.sample(), {}]),
    undefined,
  ]),
  invite_code: faker.word.sample(),
  invited_flatpaks: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => faker.word.sample()),
    undefined,
  ]),
  is_moderator: faker.datatype.boolean(),
  is_quality_moderator: faker.datatype.boolean(),
  owned_flatpaks: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => faker.word.sample()),
    undefined,
  ]),
  ...overrideResponse,
})

export const getDoRefreshDevFlatpaksAuthRefreshDevFlatpaksPostResponseMock = (
  overrideResponse: any = {},
): RefreshDevFlatpaksReturn => ({
  dev_flatpaks: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => faker.word.sample()),
  ...overrideResponse,
})

export const getDoLogoutAuthLogoutPostResponseMock =
  (): DoLogoutAuthLogoutPost200 => ({})

export const getGetDeleteuserAuthDeleteuserGetResponseMock = (
  overrideResponse: any = {},
): GetDeleteUserResult => ({
  status: faker.word.sample(),
  token: faker.word.sample(),
  ...overrideResponse,
})

export const getDoDeleteuserAuthDeleteuserPostResponseMock = (
  overrideResponse: any = {},
): DeleteUserResult => ({
  message: faker.helpers.arrayElement([
    faker.helpers.arrayElement([faker.word.sample(), {}]),
    undefined,
  ]),
  status: faker.word.sample(),
  ...overrideResponse,
})

export const getDoAgreeToPublisherAgreementAuthAcceptPublisherAgreementPostResponseMock =
  (): DoAgreeToPublisherAgreementAuthAcceptPublisherAgreementPost200 => ({})

export const getGetLoginMethodsAuthLoginGetMockHandler = (
  overrideResponse?: LoginMethod[],
) => {
  return http.get("*/auth/login", async () => {
    await delay(1000)
    return new HttpResponse(
      JSON.stringify(
        overrideResponse
          ? overrideResponse
          : getGetLoginMethodsAuthLoginGetResponseMock(),
      ),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      },
    )
  })
}

export const getStartGithubFlowAuthLoginGithubGetMockHandler = (
  overrideResponse?: StartGithubFlowAuthLoginGithubGet200,
) => {
  return http.get("*/auth/login/github", async () => {
    await delay(1000)
    return new HttpResponse(
      JSON.stringify(
        overrideResponse
          ? overrideResponse
          : getStartGithubFlowAuthLoginGithubGetResponseMock(),
      ),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      },
    )
  })
}

export const getContinueGithubFlowAuthLoginGithubPostMockHandler = (
  overrideResponse?: ContinueGithubFlowAuthLoginGithubPost200,
) => {
  return http.post("*/auth/login/github", async () => {
    await delay(1000)
    return new HttpResponse(
      JSON.stringify(
        overrideResponse
          ? overrideResponse
          : getContinueGithubFlowAuthLoginGithubPostResponseMock(),
      ),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      },
    )
  })
}

export const getStartGitlabFlowAuthLoginGitlabGetMockHandler = (
  overrideResponse?: StartGitlabFlowAuthLoginGitlabGet200,
) => {
  return http.get("*/auth/login/gitlab", async () => {
    await delay(1000)
    return new HttpResponse(
      JSON.stringify(
        overrideResponse
          ? overrideResponse
          : getStartGitlabFlowAuthLoginGitlabGetResponseMock(),
      ),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      },
    )
  })
}

export const getContinueGitlabFlowAuthLoginGitlabPostMockHandler = (
  overrideResponse?: ContinueGitlabFlowAuthLoginGitlabPost200,
) => {
  return http.post("*/auth/login/gitlab", async () => {
    await delay(1000)
    return new HttpResponse(
      JSON.stringify(
        overrideResponse
          ? overrideResponse
          : getContinueGitlabFlowAuthLoginGitlabPostResponseMock(),
      ),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      },
    )
  })
}

export const getStartGnomeFlowAuthLoginGnomeGetMockHandler = (
  overrideResponse?: StartGnomeFlowAuthLoginGnomeGet200,
) => {
  return http.get("*/auth/login/gnome", async () => {
    await delay(1000)
    return new HttpResponse(
      JSON.stringify(
        overrideResponse
          ? overrideResponse
          : getStartGnomeFlowAuthLoginGnomeGetResponseMock(),
      ),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      },
    )
  })
}

export const getContinueGnomeFlowAuthLoginGnomePostMockHandler = (
  overrideResponse?: ContinueGnomeFlowAuthLoginGnomePost200,
) => {
  return http.post("*/auth/login/gnome", async () => {
    await delay(1000)
    return new HttpResponse(
      JSON.stringify(
        overrideResponse
          ? overrideResponse
          : getContinueGnomeFlowAuthLoginGnomePostResponseMock(),
      ),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      },
    )
  })
}

export const getStartKdeFlowAuthLoginKdeGetMockHandler = (
  overrideResponse?: StartKdeFlowAuthLoginKdeGet200,
) => {
  return http.get("*/auth/login/kde", async () => {
    await delay(1000)
    return new HttpResponse(
      JSON.stringify(
        overrideResponse
          ? overrideResponse
          : getStartKdeFlowAuthLoginKdeGetResponseMock(),
      ),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      },
    )
  })
}

export const getContinueKdeFlowAuthLoginKdePostMockHandler = (
  overrideResponse?: ContinueKdeFlowAuthLoginKdePost200,
) => {
  return http.post("*/auth/login/kde", async () => {
    await delay(1000)
    return new HttpResponse(
      JSON.stringify(
        overrideResponse
          ? overrideResponse
          : getContinueKdeFlowAuthLoginKdePostResponseMock(),
      ),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      },
    )
  })
}

export const getContinueGoogleFlowAuthLoginGooglePostMockHandler = (
  overrideResponse?: ContinueGoogleFlowAuthLoginGooglePost200,
) => {
  return http.post("*/auth/login/google", async () => {
    await delay(1000)
    return new HttpResponse(
      JSON.stringify(
        overrideResponse
          ? overrideResponse
          : getContinueGoogleFlowAuthLoginGooglePostResponseMock(),
      ),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      },
    )
  })
}

export const getGetUserinfoAuthUserinfoGetMockHandler = (
  overrideResponse?: UserInfo,
) => {
  return http.get("*/auth/userinfo", async () => {
    await delay(1000)
    return new HttpResponse(
      JSON.stringify(
        overrideResponse
          ? overrideResponse
          : getGetUserinfoAuthUserinfoGetResponseMock(),
      ),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      },
    )
  })
}

export const getDoRefreshDevFlatpaksAuthRefreshDevFlatpaksPostMockHandler = (
  overrideResponse?: RefreshDevFlatpaksReturn,
) => {
  return http.post("*/auth/refresh-dev-flatpaks", async () => {
    await delay(1000)
    return new HttpResponse(
      JSON.stringify(
        overrideResponse
          ? overrideResponse
          : getDoRefreshDevFlatpaksAuthRefreshDevFlatpaksPostResponseMock(),
      ),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      },
    )
  })
}

export const getDoLogoutAuthLogoutPostMockHandler = (
  overrideResponse?: DoLogoutAuthLogoutPost200,
) => {
  return http.post("*/auth/logout", async () => {
    await delay(1000)
    return new HttpResponse(
      JSON.stringify(
        overrideResponse
          ? overrideResponse
          : getDoLogoutAuthLogoutPostResponseMock(),
      ),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      },
    )
  })
}

export const getGetDeleteuserAuthDeleteuserGetMockHandler = (
  overrideResponse?: GetDeleteUserResult,
) => {
  return http.get("*/auth/deleteuser", async () => {
    await delay(1000)
    return new HttpResponse(
      JSON.stringify(
        overrideResponse
          ? overrideResponse
          : getGetDeleteuserAuthDeleteuserGetResponseMock(),
      ),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      },
    )
  })
}

export const getDoDeleteuserAuthDeleteuserPostMockHandler = (
  overrideResponse?: DeleteUserResult,
) => {
  return http.post("*/auth/deleteuser", async () => {
    await delay(1000)
    return new HttpResponse(
      JSON.stringify(
        overrideResponse
          ? overrideResponse
          : getDoDeleteuserAuthDeleteuserPostResponseMock(),
      ),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      },
    )
  })
}

export const getDoAgreeToPublisherAgreementAuthAcceptPublisherAgreementPostMockHandler =
  (
    overrideResponse?: DoAgreeToPublisherAgreementAuthAcceptPublisherAgreementPost200,
  ) => {
    return http.post("*/auth/accept-publisher-agreement", async () => {
      await delay(1000)
      return new HttpResponse(
        JSON.stringify(
          overrideResponse
            ? overrideResponse
            : getDoAgreeToPublisherAgreementAuthAcceptPublisherAgreementPostResponseMock(),
        ),
        {
          status: 200,
          headers: {
            "Content-Type": "application/json",
          },
        },
      )
    })
  }

export const getDoChangeDefaultAccountAuthChangeDefaultAccountPostMockHandler =
  () => {
    return http.post("*/auth/change-default-account", async () => {
      await delay(1000)
      return new HttpResponse(null, {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      })
    })
  }
export const getAuthMock = () => [
  getGetLoginMethodsAuthLoginGetMockHandler(),
  getStartGithubFlowAuthLoginGithubGetMockHandler(),
  getContinueGithubFlowAuthLoginGithubPostMockHandler(),
  getStartGitlabFlowAuthLoginGitlabGetMockHandler(),
  getContinueGitlabFlowAuthLoginGitlabPostMockHandler(),
  getStartGnomeFlowAuthLoginGnomeGetMockHandler(),
  getContinueGnomeFlowAuthLoginGnomePostMockHandler(),
  getStartKdeFlowAuthLoginKdeGetMockHandler(),
  getContinueKdeFlowAuthLoginKdePostMockHandler(),
  getContinueGoogleFlowAuthLoginGooglePostMockHandler(),
  getGetUserinfoAuthUserinfoGetMockHandler(),
  getDoRefreshDevFlatpaksAuthRefreshDevFlatpaksPostMockHandler(),
  getDoLogoutAuthLogoutPostMockHandler(),
  getGetDeleteuserAuthDeleteuserGetMockHandler(),
  getDoDeleteuserAuthDeleteuserPostMockHandler(),
  getDoAgreeToPublisherAgreementAuthAcceptPublisherAgreementPostMockHandler(),
  getDoChangeDefaultAccountAuthChangeDefaultAccountPostMockHandler(),
]
