"""Add content rating column

Revision ID: 850fec56d92a
Revises: aa175eb8c7b6
Create Date: 2025-05-28 18:49:47.901730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '850fec56d92a'
down_revision = 'aa175eb8c7b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('content_rating_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'content_rating_details')
    # ### end Alembic commands ###
