"""Make id foreign key

Revision ID: d7e1d2130fdb
Revises: 897681b5de80
Create Date: 2025-01-25 15:39:00.500887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e1d2130fdb'
down_revision = '897681b5de80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_favorite_app', 'apps', ['app_id'], ['app_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_favorite_app', type_='foreignkey')
    # ### end Alembic commands ###
