"""Add User Role Unique Index

Revision ID: ebfa674573a8
Revises: 60a0f4c43817
Create Date: 2024-12-23 01:04:08.703602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebfa674573a8'
down_revision = '60a0f4c43817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('flathubuser_role_unique', 'flathubuser_role', ['flathubuser_id', 'role_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('flathubuser_role_unique', table_name='flathubuser_role')
    # ### end Alembic commands ###
