/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation } from "@tanstack/react-query"
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query"
import type { BuildNotificationRequest, HTTPValidationError } from ".././model"

/**
 * @summary Build Notification
 */
export type buildNotificationEmailsBuildNotificationPostResponse = {
  data: unknown
  status: number
  headers: Headers
}

export const getBuildNotificationEmailsBuildNotificationPostUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_BASE_URI}/emails/build-notification`
}

export const buildNotificationEmailsBuildNotificationPost = async (
  buildNotificationRequest: BuildNotificationRequest,
  options?: RequestInit,
): Promise<buildNotificationEmailsBuildNotificationPostResponse> => {
  const res = await fetch(
    getBuildNotificationEmailsBuildNotificationPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(buildNotificationRequest),
    },
  )
  const data = await res.json()

  return { status: res.status, data, headers: res.headers }
}

export const getBuildNotificationEmailsBuildNotificationPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof buildNotificationEmailsBuildNotificationPost>>,
    TError,
    { data: BuildNotificationRequest },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof buildNotificationEmailsBuildNotificationPost>>,
  TError,
  { data: BuildNotificationRequest },
  TContext
> => {
  const { mutation: mutationOptions, fetch: fetchOptions } = options ?? {}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof buildNotificationEmailsBuildNotificationPost>>,
    { data: BuildNotificationRequest }
  > = (props) => {
    const { data } = props ?? {}

    return buildNotificationEmailsBuildNotificationPost(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type BuildNotificationEmailsBuildNotificationPostMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof buildNotificationEmailsBuildNotificationPost>>
  >
export type BuildNotificationEmailsBuildNotificationPostMutationBody =
  BuildNotificationRequest
export type BuildNotificationEmailsBuildNotificationPostMutationError =
  HTTPValidationError

/**
 * @summary Build Notification
 */
export const useBuildNotificationEmailsBuildNotificationPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof buildNotificationEmailsBuildNotificationPost>>,
    TError,
    { data: BuildNotificationRequest },
    TContext
  >
  fetch?: RequestInit
}): UseMutationResult<
  Awaited<ReturnType<typeof buildNotificationEmailsBuildNotificationPost>>,
  TError,
  { data: BuildNotificationRequest },
  TContext
> => {
  const mutationOptions =
    getBuildNotificationEmailsBuildNotificationPostMutationOptions(options)

  return useMutation(mutationOptions)
}
