/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ListPipelinesApiPipelinesGetGroup =
  | (typeof ListPipelinesApiPipelinesGetGroup)[keyof typeof ListPipelinesApiPipelinesGetGroup]
  | null

export const ListPipelinesApiPipelinesGetGroup = {
  "in-progress": "in-progress",
  "awaiting-publishing": "awaiting-publishing",
  completed: "completed",
} as const
