/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { PipelineStatus } from "./pipelineStatus"
import type { PipelineResponseRepo } from "./pipelineResponseRepo"
import type { PipelineResponseParams } from "./pipelineResponseParams"
import type { PipelineTrigger } from "./pipelineTrigger"
import type { PipelineResponseLogUrl } from "./pipelineResponseLogUrl"
import type { PipelineResponseBuildId } from "./pipelineResponseBuildId"
import type { PipelineResponseCommitJobId } from "./pipelineResponseCommitJobId"
import type { PipelineResponsePublishJobId } from "./pipelineResponsePublishJobId"
import type { PipelineResponseUpdateRepoJobId } from "./pipelineResponseUpdateRepoJobId"
import type { PipelineResponseStartedAt } from "./pipelineResponseStartedAt"
import type { PipelineResponseFinishedAt } from "./pipelineResponseFinishedAt"
import type { PipelineResponsePublishedAt } from "./pipelineResponsePublishedAt"

export interface PipelineResponse {
  id: string
  app_id: string
  status: PipelineStatus
  repo?: PipelineResponseRepo
  params: PipelineResponseParams
  triggered_by: PipelineTrigger
  log_url?: PipelineResponseLogUrl
  build_id?: PipelineResponseBuildId
  commit_job_id?: PipelineResponseCommitJobId
  publish_job_id?: PipelineResponsePublishJobId
  update_repo_job_id?: PipelineResponseUpdateRepoJobId
  created_at: string
  started_at?: PipelineResponseStartedAt
  finished_at?: PipelineResponseFinishedAt
  published_at?: PipelineResponsePublishedAt
}
