/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { PipelineSummaryRepo } from "./pipelineSummaryRepo"
import type { PipelineSummaryStartedAt } from "./pipelineSummaryStartedAt"
import type { PipelineSummaryFinishedAt } from "./pipelineSummaryFinishedAt"
import type { PipelineSummaryPublishedAt } from "./pipelineSummaryPublishedAt"

export interface PipelineSummary {
  id: string
  app_id: string
  status: string
  repo?: PipelineSummaryRepo
  triggered_by: string
  created_at: string
  started_at?: PipelineSummaryStartedAt
  finished_at?: PipelineSummaryFinishedAt
  published_at?: PipelineSummaryPublishedAt
}
