name: 🚀 Deploy backend-node

on:
  workflow_run:
    workflows:
      - "Backend node CI"
    branches:
      - main
    types: [completed]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
    concurrency:
      group: arm64-build_push_docker_backend_node_prod
      cancel-in-progress: true
    steps:
      # 6.0.2
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        # 4.0.0
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5

      - name: Login to ghcr.io
        # 4.1.0
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push production image
        # 7.1.0
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
        with:
          context: backend-node
          file: backend-node/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          no-cache: true
          platforms: linux/arm64
          provenance: false
          build-args: |
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            GITHUB_SHA=${{ github.sha }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/backend-node:${{ github.sha }}-arm64
            ghcr.io/${{ github.repository_owner }}/backend-node:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/backend-node:arm64-latest
            ghcr.io/${{ github.repository_owner }}/backend-node:latest
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=ssh://git@github.com:${{ github.repository }}.git
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
