name: Backend node CI

on:
  push:
    branches: main
    paths:
      - "backend-node/**"
      - ".github/workflows/backend_node_ci.yml"
  pull_request:
    branches: main
    paths:
      - "backend-node/**"
      - ".github/workflows/backend_node_ci.yml"
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend-node
    permissions:
      contents: read
    steps:
      # 6.0.2
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - name: Set up Node.js
        # 6.4.0
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: "24"

      - name: Corepack enable
        run: corepack enable pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format
        run: pnpm format

      - name: Test
        run: pnpm test

      - name: Build application
        run: pnpm build
        env:
          CI: true
          GITHUB_SHA: ${{ github.sha }}
